name:  learngithubactions

jobs:
  job1:
    name: job1
    runs-on: ubuntu-latest
    steps:
      - name: print date
        run: echo date
  job2:
    name: job2
    runs-on: windows-latest
    steps:
      - name: print date
        run: echo date
  job3:
    name: job3
    runs-on: macos-latest    
    steps:
      - name: print date
        run: echo date
  job4:
    name: job4
    needs: [job1, job2, job3]
    runs-on: ubuntu-latest  
    steps:
      - name: print date
        run: echo date
      
